AllCops:
  Include:
    - "*.gemspec"
    - ".simplecov"
    - "Gemfile"
    - "Guardfile"
    - "Rakefile"
    - "tasks/*.rake"
Layout/LineLength:
  Max: 120
Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false
Metrics/BlockLength:
  Enabled: false
Naming/VariableNumber:
  EnforcedStyle: snake_case
Style/HashSyntax:
  EnforcedStyle: hash_rockets
Style/StringLiterals:
  EnforcedStyle: double_quotes
