addons:
  code_climate:
    repo_token:
      secure: iy+p8jxKVMujhB7dQI2AxKXrDdljQoB1PUQQS3pxW6oCpg9xXPFtzwy9qq5I3NnKwVK8L/553fSAVB9rR94P889Z8dGO+HiJZEyGRvBbv9lXVq0K0Uv0e/tHH8C6xzEKSy2lmCqjNaNvkTD7+HAMrilwAX7OoCcDFIydbNzerD42BtGadqrTxYBhG7N1DZDs/UfpEb9sfPBrgQDD00QcN81DIk2N5JJ3mjND1PlgoLU7Ju99TArOvGZiM1gxkF0ZB+OAseltlrPCzDMH6KGFnNFMwsYO1tVaoYDunvXietkNbgD9P8rKH0SgPYqZH98+qMm3sQDoP0vV2beP2JsVtZGRRDy136FniD0F/5Fyu9p4VhDdTCF9ExPU7NisWdB+ABP83wwI56WObTX3xOR1nl3X7wwiOiOFUPOF8QG1jUxzgG38+TM7+dclB6clek8dnCuIB4PdwZzmUY5jeltRyPXRxms079li9rnduJbKeUGWg96mg8YQDq4hIugw6I1WJIVx36abuvrxRBRDoL5ya7fT8Ha17m0etVqUXrkropOfG9mPNsU3njKIfjdFv+S61dpqBq5wnPj7cj7rjnCpmhdI4Vsizu7nBfAc0zgeBi3RhFgfU6q1bTBEK8BKeD2Vy53sLptsnARpULRNdFGCvnbyWGKO4kgWx6WoIwE6CvM=
before_install: rm coverage
gemfile: gemfiles/travis.rb
language: ruby
matrix:
  allow_failures:
    # TODO: Disallow failures for jruby-1.7 and jruby-9 once https://github.com/jruby/jruby/issues/4340 is solved.
    - rvm: jruby-1.7.26
    - rvm: jruby-9.1.5.0
    - rvm: jruby-head
    - rvm: mruby-head
    - rvm: rbx-2
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/travis_1.8.7.rb
    - rvm: 1.9.2
      gemfile: gemfiles/travis_1.9.2.rb
    - rvm: 1.9.3
      gemfile: gemfiles/travis_1.9.3.rb
    - rvm: ree
      gemfile: gemfiles/travis_1.8.7.rb
rvm:
- 2.0.0-p648
- 2.1.9
- 2.2.6
- 2.3.0
- 2.3.1
- 2.3.2
- 2.3.3
- jruby-1.7.26
- jruby-9.1.5.0
- jruby-head
- mruby-head
- rbx-2
- ruby-head
