addons:
  code_climate:
    repo_token: 9188009ca208f59c584e066297b7278bd9ccf6e8fdb0fef8144fe3956075e216
before_install: rm coverage
gemfile: gemfiles/travis.rb
language: ruby
matrix:
  allow_failures:
    # TODO: Disallow failures for jruby-1.7 and jruby-9 once https://github.com/jruby/jruby/issues/4340 is solved.
    - rvm: jruby-1.7.26
    - rvm: jruby-9.1.5.0
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/travis_1.8.7.rb
    - rvm: 1.9.2
      gemfile: gemfiles/travis_1.9.2.rb
    - rvm: 1.9.3
      gemfile: gemfiles/travis_1.9.3.rb
    - rvm: ree
      gemfile: gemfiles/travis_1.8.7.rb
rvm:
- 2.0.0-p648
- 2.1.10
- 2.2.7
- 2.3.4
- 2.4.0
- 2.4.1
- jruby-1.7.26
- jruby-9.1.5.0
- ruby-head
